project:
  type: website

website:
  title: "Alex Wainwright"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/alexwhitelockw
      - icon: linkedin
        href: www.linkedin.com/in/alexander-whitelock-wainwright
  google-analytics: "G-95CSX18B3H"
format:
  html:
    theme: lux
    css: styles.css

editor: visual

